version: 2
jobs:
    build:
        docker:
            - image: rustlang/rust:nightly
        steps:
            - checkout
            - run: cargo test
            - run: cargo fmt -- --check
            - run: cargo clean
            - run: cargo clippy -- -D clippy::all
            - run: cargo build
workflows:
    version: 2
    test_fmt_build:
        jobs:
            - build
